# Generated by Django 2.2.3 on 2019-07-12 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('slug', models.SlugField(max_length=255, verbose_name='label_slug')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label_project',
                'verbose_name_plural': 'label_project_plural',
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('slug', models.SlugField(max_length=255, verbose_name='label_slug')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
                ('content', models.TextField(verbose_name='label_content')),
                ('audio_url', models.URLField(blank=True, verbose_name='label_audio_url')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_entry', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reading.Project')),
            ],
            options={
                'verbose_name': 'label_entry',
                'verbose_name_plural': 'label_entry_plural',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
