# Generated by Django 3.0.2 on 2020-02-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_status', models.IntegerField(choices=[(3, 'label_acccess_public'), (2, 'label_acccess_protected'), (1, 'label_acccess_private')], default=3, verbose_name='label_access_status')),
                ('slug', models.SlugField(max_length=255, verbose_name='label_slug')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_readingproject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label_project',
                'verbose_name_plural': 'label_project_plural',
                'abstract': False,
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('role', models.IntegerField(choices=[(4, 'label_role_admin'), (3, 'label_role_editor'), (2, 'label_role_author'), (1, 'label_role_contributor')], default=1, verbose_name='label_role')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_readingprojectmember', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_publish_members', to='reading.ReadingProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='label_slug')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('description', models.TextField(blank=True, verbose_name='label_description')),
                ('content', models.TextField(verbose_name='label_content')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_post', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='reading.ReadingProject')),
            ],
            options={
                'verbose_name': 'label_post',
                'verbose_name_plural': 'label_post_plural',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='label_slug')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='label_date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='label_date_updated')),
                ('name', models.CharField(max_length=255, verbose_name='label_name')),
                ('url', models.URLField(verbose_name='label_url')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_audio', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='reading.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
