# Generated by Django 3.0.5 on 2020-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_url',
            field=models.URLField(blank=True, verbose_name='label_banner_url'),
        ),
    ]
